# **Import libraries and loading datasets**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import zscore
from sklearn.neighbors import LocalOutlierFactor
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import normalize
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error, accuracy_score, precision_score, recall_score
from sklearn import metrics
from sklearn.metrics import classification_report

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
development=pd.read_csv('/content/drive/MyDrive/development.csv')
evaluation=pd.read_csv('/content/drive/MyDrive/evaluation.csv')

## Finding missing values

In [ ]:
# Count the number of missing values in each column
missing_count_per_column = development.isnull().sum()

# Display the count of missing values per column
print("Missing Values Count per Column:")
print(missing_count_per_column)

Missing Values Count per Column:
x              0
y              0
pmax[0]        0
negpmax[0]     0
area[0]        0
              ..
pmax[17]       0
negpmax[17]    0
area[17]       0
tmax[17]       0
rms[17]        0
Length: 92, dtype: int64

## Finding duplicated data

In [ ]:
development.duplicated().sum()

0

## Development output

In [ ]:
output1=development['x']
output2=development['y']
development_output = pd.concat([output1, output2], axis=1)
development_output

            x      y
0       200.0  200.0
1       200.0  200.0
2       200.0  200.0
3       200.0  200.0
4       200.0  200.0
...       ...    ...
385495  600.0  595.0
385496  600.0  595.0
385497  600.0  595.0
385498  600.0  595.0
385499  600.0  595.0

[385500 rows x 2 columns]

## Development input

In [ ]:
development_input =development.drop(columns=['x','y'],axis=1)
development_input

,pmax[0],negpmax[0],area[0],tmax[0],rms[0],pmax[1],negpmax[1],area[1],tmax[1],rms[1],...,pmax[16],negpmax[16],area[16],tmax[16],rms[16],pmax[17],negpmax[17],area[17],tmax[17],rms[17]
0,4.066907,-17.690173,2.847932,0.600000,2.007042,5.409161,-17.721210,4.538778,22.600000,1.563902,...,607.109118,-36.282996,583.899899,72.373094,0.374498,614.916861,-39.848523,591.852768,72.331028,0.405595
1,5.916801,-4.717111,5.792778,79.765174,1.564535,4.414289,-4.736827,3.720435,111.875058,1.228058,...,630.348007,-39.715988,580.042799,71.029155,0.403258,624.950701,-41.266681,586.569646,71.089058,0.405890
2,4.286652,-5.316132,2.356390,74.600000,1.404622,4.567191,-5.985437,3.490490,107.800000,1.015408,...,613.880342,-40.679678,580.407491,71.892264,0.568777,596.437125,-42.712286,574.091695,71.943934,0.498019
3,4.003635,-4.617459,2.189005,43.000000,1.512162,5.019058,-4.229949,6.786200,175.600000,1.350620,...,600.714957,-43.206601,579.882635,72.357388,0.255483,591.763739,-50.681940,584.099483,72.333282,0.336454
4,4.448146,-4.848743,3.997002,196.667482,1.101113,3.250262,-5.783587,2.449456,159.800000,0.759515,...,609.723785,-43.570892,590.156125,71.249130,0.413855,606.917023,-49.923819,584.316142,71.242904,0.293824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385495,5.051422,-3.872162,14.537390,32.000000,1.103550,49.819376,-26.266623,24.781403,71.000000,1.021450,...,581.954264,-39.634247,580.419676,71.167754,0.714250,614.629732,-47.182980,594.565758,71.359798,0.345872
385496,4.067664,-5.534358,2.011714,40.200000,1.895393,51.016495,-26.138474,27.090894,71.400000,1.570939,...,591.334030,-40.229095,589.105579,71.562414,0.325978,589.602095,-49.995053,588.799525,71.539605,0.318873
385497,4.243555,-5.801462,3.199481,150.891763,1.248541,46.661682,-30.943115,24.980347,71.200000,1.255832,...,619.698505,-46.600293,582.079851,71.420761,0.430833,610.999390,-43.620535,589.163170,71.569655,0.301635
385498,14.552444,-5.017258,6.367075,72.200000,1.215713,46.515765,-22.520367,33.163073,71.400000,1.465443,...,597.935632,-43.848615,589.201047,71.426835,0.474301,611.263138,-49.387009,587.916994,71.466307,0.408242
385499,4.203323,-21.787461,3.241678,65.200000,1.780837,53.988147,-26.616895,31.294717,71.600000,1.207622,...,605.837434,-43.600342,583.723657,71.814597,0.509508,581.580222,-51.947507,582.576141,72.015844,0.354110

# **Feature selection process**

## Droping Columns

In [ ]:
rf = RandomForestRegressor(n_estimators=100,random_state=42).fit(development_input, development_output)

In [ ]:
featureImportance=rf.feature_importances_

In [ ]:
featureImportance

array([1.06224681e-05, 1.06184777e-05, 9.79852121e-06, 9.85721990e-06,
       1.01971775e-05, 1.31439559e-03, 4.44370652e-03, 2.83059849e-05,
       6.06709520e-06, 1.03774905e-05, 1.93189230e-03, 1.66791940e-04,
       1.52494845e-05, 8.08801305e-06, 1.02371936e-05, 4.33224073e-03,
       1.03756732e-02, 2.00477078e-04, 5.04327544e-06, 1.01741636e-05,
       6.14415107e-03, 1.93142477e-03, 2.40555184e-05, 6.63383794e-06,
       1.01453052e-05, 8.13502844e-02, 4.71540619e-03, 1.42046026e-04,
       3.81904116e-06, 1.01630060e-05, 1.24100612e-03, 3.01729260e-03,
       2.75738838e-05, 6.89840507e-06, 1.01775820e-05, 1.12481698e-05,
       1.03986918e-05, 1.03235009e-05, 9.94622934e-06, 1.01974764e-05,
       3.59044815e-01, 5.36304515e-03, 3.35269673e-05, 5.37065676e-06,
       1.03427683e-05, 2.16978393e-02, 1.25399478e-03, 2.06807969e-05,
       6.50334051e-06, 1.02239026e-05, 1.61551469e-01, 8.05193232e-03,
       6.31507846e-05, 4.12216499e-06, 1.02102916e-05, 2.41240278e-01,
       1.28889716e-02, 6.53232221e-05, 4.89500073e-06, 1.02756574e-05,
       1.13170248e-05, 1.07173757e-05, 1.00063367e-05, 9.77228020e-06,
       1.01659080e-05, 3.65434106e-02, 2.68317514e-02, 9.60052141e-05,
       3.14040567e-06, 1.03671889e-05, 9.46572920e-04, 2.02073455e-03,
       4.75456260e-05, 6.13338561e-06, 1.02516427e-05, 3.19343991e-04,
       1.04690972e-05, 3.73137757e-05, 5.34460978e-06, 1.02803150e-05,
       1.31266910e-05, 1.25783526e-05, 1.10565483e-05, 5.80798718e-06,
       1.16619843e-05, 1.32085626e-05, 1.50651012e-05, 1.12329879e-05,
       5.29806536e-06, 1.03438695e-05])

In [ ]:
x = []
for i in range(90):
  x.append(i)

In [ ]:
feature_names=np.array(development.columns)[2:]
feature_names

In [ ]:
sorted_feature_importance=sorted(zip(featureImportance, x), reverse=True)
sorted_feature_importance

[(0.35904481549570055, 40),
 (0.24124027771802242, 55),
 (0.1615514685780684, 50),
 (0.08135028439136618, 25),
 (0.036543410559659324, 65),
 (0.026831751446283407, 66),
 (0.02169783926844672, 45),
 (0.012888971636792874, 56),
 (0.010375673162633875, 16),
 (0.008051932324243187, 51),
 (0.006144151066389221, 20),
 (0.005363045153073716, 41),
 (0.004715406192529674, 26),
 (0.004443706518639886, 6),
 (0.00433224072911098, 15),
 (0.003017292599555394, 31),
 (0.0020207345494707755, 71),
 (0.0019318922978726035, 10),
 (0.0019314247679771163, 21),
 (0.001314395588526329, 5),
 (0.0012539947798651289, 46),
 (0.001241006117015447, 30),
 (0.0009465729201862615, 70),
 (0.00031934399067106746, 75),
 (0.00020047707829578483, 17),
 (0.00016679194043449401, 11),
 (0.0001420460263993425, 27),
 (9.600521408781006e-05, 67),
 (6.532322206395929e-05, 57),
 (6.315078461007872e-05, 52),
 (4.7545626012864796e-05, 72),
 (3.731377572968279e-05, 77),
 (3.352696732121246e-05, 42),
 (2.830598487391497e-05, 7),
 (2.757388377843652e-05, 32),
 (2.4055518350714405e-05, 22),
 (2.068079688445183e-05, 47),
 (1.5249484523170798e-05, 12),
 (1.5065101220716188e-05, 86),
 (1.3208562616601315e-05, 85),
 (1.3126690996550292e-05, 80),
 (1.2578352596730722e-05, 81),
 (1.1661984289632092e-05, 84),
 (1.1317024770218808e-05, 60),
 (1.1248169772018016e-05, 35),
 (1.1232987871959362e-05, 87),
 (1.105654832282401e-05, 82),
 (1.0717375675553485e-05, 61),
 (1.062246807775333e-05, 0),
 (1.0618477683335843e-05, 1),
 (1.0469097191828742e-05, 76),
 (1.0398691793411338e-05, 36),
 (1.0377490463484643e-05, 9),
 (1.0367188909553467e-05, 69),
 (1.034386949211336e-05, 89),
 (1.034276833059291e-05, 44),
 (1.0323500902904286e-05, 37),
 (1.0280314990521056e-05, 79),
 (1.0275657434004005e-05, 59),
 (1.0251642671289364e-05, 74),
 (1.023719364515426e-05, 14),
 (1.0223902635430798e-05, 49),
 (1.0210291559370538e-05, 54),
 (1.0197476419061464e-05, 39),
 (1.0197177545259806e-05, 4),
 (1.0177581988647329e-05, 34),
 (1.0174163608040132e-05, 19),
 (1.0165907985408606e-05, 64),
 (1.0163005982599103e-05, 29),
 (1.0145305249053002e-05, 24),
 (1.0006336720393645e-05, 62),
 (9.946229337999095e-06, 38),
 (9.857219898994315e-06, 3),
 (9.798521212864657e-06, 2),
 (9.772280201177508e-06, 63),
 (8.088013054393086e-06, 13),
 (6.898405067703512e-06, 33),
 (6.633837938919366e-06, 23),
 (6.503340511466803e-06, 48),
 (6.133385614130385e-06, 73),
 (6.0670952017153885e-06, 8),
 (5.807987176743064e-06, 83),
 (5.370656760324802e-06, 43),
 (5.344609782022802e-06, 78),
 (5.298065358802489e-06, 88),
 (5.04327544368508e-06, 18),
 (4.8950007303662855e-06, 58),
 (4.122164992327082e-06, 53),
 (3.81904116418068e-06, 28),
 (3.140405673764595e-06, 68)]

In [ ]:
selected_features = sorted([row[1] for row in sorted_feature_importance[: 60]])

print(selected_features)

[0, 1, 5, 6, 7, 9, 10, 11, 12, 15, 16, 17, 20, 21, 22, 25, 26, 27, 30, 31, 32, 35, 36, 37, 40, 41, 42, 44, 45, 46, 47, 50, 51, 52, 55, 56, 57, 59, 60, 61, 65, 66, 67, 69, 70, 71, 72, 74, 75, 76, 77, 79, 80, 81, 82, 84, 85, 86, 87, 89]

In [ ]:
evaluation_withOutID=evaluation.drop(columns=['Id'],axis=1)

In [ ]:
columns_to_keep = selected_features

remained_development=development_input.iloc[:, columns_to_keep]

remained_evaluation=evaluation_withOutID.iloc[:, columns_to_keep]

# **Normazlization and Standardization**

## Normalizing development input

In [ ]:
normalized_dev_input = normalize(remained_development, norm='l2')
normalized_dev_input

array([[ 3.31052757e-03, -1.44000859e-02,  4.40314445e-03, ...,
        -3.24373393e-02,  4.81777682e-01,  3.30160841e-04],
       [ 4.76229730e-03, -3.79669506e-03,  3.55296021e-03, ...,
        -3.32146069e-02,  4.72116482e-01,  3.26691883e-04],
       [ 3.54248340e-03, -4.39324434e-03,  3.77432043e-03, ...,
        -3.52973788e-02,  4.74428642e-01,  4.11562517e-04],
       ...,
       [ 3.45605286e-03, -4.72484960e-03,  3.80023928e-02, ...,
        -3.55256099e-02,  4.79828613e-01,  2.45658703e-04],
       [ 1.19345545e-02, -4.11468572e-03,  3.81478823e-02, ...,
        -4.05026076e-02,  4.82154557e-01,  3.34802220e-04],
       [ 3.49016494e-03, -1.80908832e-02,  4.48282279e-02, ...,
        -4.31338136e-02,  4.83733143e-01,  2.94029938e-04]])

## Standardizing the normalized development input

In [ ]:
standardized_data = (normalized_dev_input - np.mean(normalized_dev_input, axis=0)) / np.std(normalized_dev_input, axis=0)
standard_input = pd.DataFrame(standardized_data, columns=remained_development.columns)
standard_input

,pmax[0],negpmax[0],pmax[1],negpmax[1],area[1],rms[1],pmax[2],negpmax[2],area[2],pmax[3],...,area[15],rms[15],pmax[16],negpmax[16],area[16],rms[16],pmax[17],negpmax[17],area[17],rms[17]
0,-0.565511,-2.272103,-0.664929,-0.773900,-0.711889,0.625853,-0.358411,-1.779834,-0.669723,-0.893563,...,-0.270042,-0.529441,-0.479149,1.917423,-0.438641,-0.273353,0.015865,2.111533,0.286129,0.373378
1,0.628786,0.070612,-0.726702,0.405937,-0.812982,-0.388266,-0.568548,0.278333,-0.649195,-0.890252,...,1.230336,0.376814,0.602216,1.002831,-1.328546,-0.193299,0.218164,1.842999,-0.725228,0.322173
2,-0.374693,-0.061190,-0.710618,0.279891,-0.828859,-0.920272,-0.438245,0.244650,-0.702798,-0.848009,...,-0.688028,-1.011409,0.598701,0.381776,0.019355,0.397037,-0.614791,1.123436,-0.483185,1.574933
3,-0.556913,0.063222,-0.682358,0.439717,-0.432575,0.081697,-0.595897,0.031398,-0.994716,-0.891516,...,-0.771660,-0.215559,-0.142876,-0.453945,0.162688,-0.650480,-0.782152,-1.206106,0.571669,-0.380536
4,-0.299178,0.034182,-0.791906,0.304458,-0.956391,-1.699138,-0.530219,0.098322,-0.441540,-0.841604,...,-0.147900,0.288519,-0.153051,-0.363420,0.285939,-0.138271,-0.369699,-0.773957,-0.171602,-0.956533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385495,0.140699,0.203389,2.002622,-1.580195,1.707734,-0.906444,6.139764,-3.114414,4.727988,1.456409,...,0.366036,1.624438,-1.622017,0.722978,-0.046251,0.881762,0.568282,-0.135220,1.220203,-0.286575
385496,-0.514577,-0.104320,2.088408,-1.579412,1.997718,0.730619,6.492925,-3.744114,4.716175,1.342631,...,1.025154,-0.151866,-0.802168,0.481174,0.944088,-0.413704,-0.949510,-1.002260,0.954805,-0.597700
385497,-0.445795,-0.134455,1.776362,-1.971821,1.692179,-0.265891,6.842982,-3.793099,5.040131,1.842649,...,0.074278,1.988276,0.383958,-1.248684,-0.569809,-0.086535,-0.226245,1.044586,0.082096,-0.873943
385498,6.529037,0.000355,1.786933,-1.223448,2.681626,0.372070,5.329212,-3.520234,4.372312,1.289530,...,0.834046,-1.254139,-0.793601,-0.499473,0.394643,0.068072,0.077524,-0.674885,0.325581,0.441889
385499,-0.417732,-3.087549,2.272321,-1.627203,2.506603,-0.337330,6.726986,-3.390666,4.502241,1.520682,...,0.292491,0.683238,0.248376,-0.590626,0.550505,0.206400,-1.437454,-1.583924,0.490831,-0.159944

## Showing normalized and standardized development data

In [ ]:
norm_development=pd.concat([development_output,standard_input],axis=1)
norm_development

,x,y,pmax[0],negpmax[0],pmax[1],negpmax[1],area[1],rms[1],pmax[2],negpmax[2],...,area[15],rms[15],pmax[16],negpmax[16],area[16],rms[16],pmax[17],negpmax[17],area[17],rms[17]
0,200.0,200.0,-0.565511,-2.272103,-0.664929,-0.773900,-0.711889,0.625853,-0.358411,-1.779834,...,-0.270042,-0.529441,-0.479149,1.917423,-0.438641,-0.273353,0.015865,2.111533,0.286129,0.373378
1,200.0,200.0,0.628786,0.070612,-0.726702,0.405937,-0.812982,-0.388266,-0.568548,0.278333,...,1.230336,0.376814,0.602216,1.002831,-1.328546,-0.193299,0.218164,1.842999,-0.725228,0.322173
2,200.0,200.0,-0.374693,-0.061190,-0.710618,0.279891,-0.828859,-0.920272,-0.438245,0.244650,...,-0.688028,-1.011409,0.598701,0.381776,0.019355,0.397037,-0.614791,1.123436,-0.483185,1.574933
3,200.0,200.0,-0.556913,0.063222,-0.682358,0.439717,-0.432575,0.081697,-0.595897,0.031398,...,-0.771660,-0.215559,-0.142876,-0.453945,0.162688,-0.650480,-0.782152,-1.206106,0.571669,-0.380536
4,200.0,200.0,-0.299178,0.034182,-0.791906,0.304458,-0.956391,-1.699138,-0.530219,0.098322,...,-0.147900,0.288519,-0.153051,-0.363420,0.285939,-0.138271,-0.369699,-0.773957,-0.171602,-0.956533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385495,600.0,595.0,0.140699,0.203389,2.002622,-1.580195,1.707734,-0.906444,6.139764,-3.114414,...,0.366036,1.624438,-1.622017,0.722978,-0.046251,0.881762,0.568282,-0.135220,1.220203,-0.286575
385496,600.0,595.0,-0.514577,-0.104320,2.088408,-1.579412,1.997718,0.730619,6.492925,-3.744114,...,1.025154,-0.151866,-0.802168,0.481174,0.944088,-0.413704,-0.949510,-1.002260,0.954805,-0.597700
385497,600.0,595.0,-0.445795,-0.134455,1.776362,-1.971821,1.692179,-0.265891,6.842982,-3.793099,...,0.074278,1.988276,0.383958,-1.248684,-0.569809,-0.086535,-0.226245,1.044586,0.082096,-0.873943
385498,600.0,595.0,6.529037,0.000355,1.786933,-1.223448,2.681626,0.372070,5.329212,-3.520234,...,0.834046,-1.254139,-0.793601,-0.499473,0.394643,0.068072,0.077524,-0.674885,0.325581,0.441889
385499,600.0,595.0,-0.417732,-3.087549,2.272321,-1.627203,2.506603,-0.337330,6.726986,-3.390666,...,0.292491,0.683238,0.248376,-0.590626,0.550505,0.206400,-1.437454,-1.583924,0.490831,-0.159944

# **Build Neural network model**

##  Splitting Trainset and Testset

In [ ]:
input_train, input_test, output_train, output_test = train_test_split(standard_input,development_output, test_size=0.01)

## Create the MLP Regressor On Train Data and Calculate accuracy metrics

In [ ]:
mlp_regressor = MLPRegressor(hidden_layer_sizes=(300,255), max_iter=400,verbose=True)

## Train the model

In [ ]:
mlp_regressor.fit(input_train, output_train)

Iteration 1, loss = 2681.36293756
Iteration 2, loss = 62.45365881
Iteration 3, loss = 26.04763151
Iteration 4, loss = 18.36749864
Iteration 5, loss = 15.64082227
Iteration 6, loss = 14.04428321
Iteration 7, loss = 13.98067218
Iteration 8, loss = 12.76292387
Iteration 9, loss = 12.45041044
Iteration 10, loss = 11.93076065
Iteration 11, loss = 11.62901924
Iteration 12, loss = 11.34962191
Iteration 13, loss = 11.08614482
Iteration 14, loss = 10.76302598
Iteration 15, loss = 10.72266876
Iteration 16, loss = 10.65716526
Iteration 17, loss = 10.33224261
Iteration 18, loss = 10.25349445
Iteration 19, loss = 10.08014781
Iteration 20, loss = 10.08700273
Iteration 21, loss = 9.83430903
Iteration 22, loss = 9.88508800
Iteration 23, loss = 9.63659727
Iteration 24, loss = 9.47138269
Iteration 25, loss = 9.47700752
Iteration 26, loss = 9.59395808
Iteration 27, loss = 9.29659375
Iteration 28, loss = 9.29571065
Iteration 29, loss = 9.19526480
Iteration 30, loss = 9.12906748
Iteration 31, loss = 8.99526138
Iteration 32, loss = 8.96893117
Iteration 33, loss = 8.84493483
Iteration 34, loss = 9.07785286
Iteration 35, loss = 8.83365970
Iteration 36, loss = 8.67187589
Iteration 37, loss = 9.02254373
Iteration 38, loss = 8.59086182
Iteration 39, loss = 8.69291777
Iteration 40, loss = 8.65715864
Iteration 41, loss = 8.51945332
Iteration 42, loss = 8.47246912
Iteration 43, loss = 8.42702709
Iteration 44, loss = 8.49037788
Iteration 45, loss = 8.39202950
Iteration 46, loss = 8.35947276
Iteration 47, loss = 8.36732341
Iteration 48, loss = 8.37593515
Iteration 49, loss = 8.29390789
Iteration 50, loss = 8.22180203
Iteration 51, loss = 8.11452393
Iteration 52, loss = 8.19358245
Iteration 53, loss = 8.09602434
Iteration 54, loss = 8.31173603
Iteration 55, loss = 8.07254234
Iteration 56, loss = 8.04652988
Iteration 57, loss = 7.88841743
Iteration 58, loss = 8.01302645
Iteration 59, loss = 7.91561634
Iteration 60, loss = 7.90456720
Iteration 61, loss = 7.97967538
Iteration 62, loss = 7.82917154
Iteration 63, loss = 7.80456469
Iteration 64, loss = 7.86323848
Iteration 65, loss = 7.93332435
Iteration 66, loss = 7.70271168
Iteration 67, loss = 7.80022695
Iteration 68, loss = 7.71534655
Iteration 69, loss = 7.79424927
Iteration 70, loss = 7.67443925
Iteration 71, loss = 7.67453617
Iteration 72, loss = 7.63376906
Iteration 73, loss = 7.57200860
Iteration 74, loss = 7.60616973
Iteration 75, loss = 7.50798816
Iteration 76, loss = 7.69058111
Iteration 77, loss = 7.46716823
Iteration 78, loss = 7.49033433
Iteration 79, loss = 7.46967803
Iteration 80, loss = 7.55268386
Iteration 81, loss = 7.48706348
Iteration 82, loss = 7.53848483
Iteration 83, loss = 7.42471346
Iteration 84, loss = 7.34375738
Iteration 85, loss = 7.36973258
Iteration 86, loss = 7.44626426
Iteration 87, loss = 7.22672139
Iteration 88, loss = 7.35697770
Iteration 89, loss = 7.33996495
Iteration 90, loss = 7.30214118
Iteration 91, loss = 7.32595871
Iteration 92, loss = 7.17851158
Iteration 93, loss = 7.24890281
Iteration 94, loss = 7.28790656
Iteration 95, loss = 7.21300600
Iteration 96, loss = 7.18602344
Iteration 97, loss = 7.12461852
Iteration 98, loss = 7.15741101
Iteration 99, loss = 7.15207716
Iteration 100, loss = 7.16499031
Iteration 101, loss = 7.13064096
Iteration 102, loss = 7.05205847
Iteration 103, loss = 7.03816119
Iteration 104, loss = 7.04109684
Iteration 105, loss = 7.15376522
Iteration 106, loss = 7.08127731
Iteration 107, loss = 7.06919656
Iteration 108, loss = 7.00540990
Iteration 109, loss = 6.93953558
Iteration 110, loss = 6.97136466
Iteration 111, loss = 7.13222726
Iteration 112, loss = 6.95754102
Iteration 113, loss = 6.94787261
Iteration 114, loss = 6.90526765
Iteration 115, loss = 6.87098973
Iteration 116, loss = 6.94757832
Iteration 117, loss = 6.94096765
Iteration 118, loss = 6.87261740
Iteration 119, loss = 6.83456774
Iteration 120, loss = 6.94745604
Iteration 121, loss = 6.85118020
Iteration 122, loss = 6.84264825
Iteration 123, loss = 6.84599146
Iteration 124, loss = 6.80878177
Iteration 125, loss = 6.80987820
Iteration 126, loss = 6.85700264
Iteration 127, loss = 6.78764600
Iteration 128, loss = 6.80956323
Iteration 129, loss = 6.87661486
Iteration 130, loss = 6.73605213
Iteration 131, loss = 6.81740283
Iteration 132, loss = 6.68589867
Iteration 133, loss = 6.68059721
Iteration 134, loss = 6.64812136
Iteration 135, loss = 6.74449890
Iteration 136, loss = 6.74429213
Iteration 137, loss = 6.65723587
Iteration 138, loss = 6.74661757
Iteration 139, loss = 6.61318712
Iteration 140, loss = 6.74662014
Iteration 141, loss = 6.63341491
Iteration 142, loss = 6.59494849
Iteration 143, loss = 6.70701300
Iteration 144, loss = 6.61009800
Iteration 145, loss = 6.63858307
Iteration 146, loss = 6.64186285
Iteration 147, loss = 6.58085469
Iteration 148, loss = 6.60078153
Iteration 149, loss = 6.55748547
Iteration 150, loss = 6.65237905
Iteration 151, loss = 6.62357798
Iteration 152, loss = 6.49071671
Iteration 153, loss = 6.53145237
Iteration 154, loss = 6.54610710
Iteration 155, loss = 6.54750993
Iteration 156, loss = 6.55915957
Iteration 157, loss = 6.53244392
Iteration 158, loss = 6.50854711
Iteration 159, loss = 6.51633261
Iteration 160, loss = 6.45412834
Iteration 161, loss = 6.53013861
Iteration 162, loss = 6.45836022
Iteration 163, loss = 6.41527730
Iteration 164, loss = 6.46762957
Iteration 165, loss = 6.54162592
Iteration 166, loss = 6.37025162
Iteration 167, loss = 6.41863876
Iteration 168, loss = 6.43851594
Iteration 169, loss = 6.40568540
Iteration 170, loss = 6.38968019
Iteration 171, loss = 6.41153419
Iteration 172, loss = 6.38477339
Iteration 173, loss = 6.44966088
Iteration 174, loss = 6.39151378
Iteration 175, loss = 6.34105267
Iteration 176, loss = 6.34398771
Iteration 177, loss = 6.40536024
Iteration 178, loss = 6.34557258
Iteration 179, loss = 6.35659578
Iteration 180, loss = 6.29097243
Iteration 181, loss = 6.34927981
Iteration 182, loss = 6.28458068
Iteration 183, loss = 6.27767812
Iteration 184, loss = 6.37223116
Iteration 185, loss = 6.29062845
Iteration 186, loss = 6.29451754
Iteration 187, loss = 6.29965185
Iteration 188, loss = 6.35827792
Iteration 189, loss = 6.19707025
Iteration 190, loss = 6.30007229
Iteration 191, loss = 6.30250060
Iteration 192, loss = 6.22834513
Iteration 193, loss = 6.19610926
Iteration 194, loss = 6.28620439
Iteration 195, loss = 6.21625683
Iteration 196, loss = 6.22215664
Iteration 197, loss = 6.20665566
Iteration 198, loss = 6.24758909
Iteration 199, loss = 6.19828179
Iteration 200, loss = 6.15707965
Iteration 201, loss = 6.22530952
Iteration 202, loss = 6.16259917
Iteration 203, loss = 6.16660659
Iteration 204, loss = 6.21959197
Iteration 205, loss = 6.15607415
Iteration 206, loss = 6.15235537
Iteration 207, loss = 6.14988413
Iteration 208, loss = 6.12109138
Iteration 209, loss = 6.15032394
Iteration 210, loss = 6.15899905
Iteration 211, loss = 6.09627695
Iteration 212, loss = 6.16547713
Iteration 213, loss = 6.10390929
Iteration 214, loss = 6.14658376
Iteration 215, loss = 6.14797144
Iteration 216, loss = 6.08717594
Iteration 217, loss = 6.06966608
Iteration 218, loss = 6.07535044
Iteration 219, loss = 6.13367867
Iteration 220, loss = 6.08960999
Iteration 221, loss = 6.04273217
Iteration 222, loss = 6.08777003
Iteration 223, loss = 6.07585638
Iteration 224, loss = 6.08058149
Iteration 225, loss = 6.07428977
Iteration 226, loss = 6.04947307
Iteration 227, loss = 6.04341745
Iteration 228, loss = 6.05174411
Iteration 229, loss = 6.08427255
Iteration 230, loss = 6.03371377
Iteration 231, loss = 6.03660665
Iteration 232, loss = 6.05069407
Iteration 233, loss = 6.02487562
Iteration 234, loss = 6.01300811
Iteration 235, loss = 5.96123720
Iteration 236, loss = 6.07671960
Iteration 237, loss = 5.98952997
Iteration 238, loss = 5.98837839
Iteration 239, loss = 5.96226869
Iteration 240, loss = 5.96277508
Iteration 241, loss = 5.96706962
Iteration 242, loss = 5.95280299
Iteration 243, loss = 6.00750244
Iteration 244, loss = 5.98470241
Iteration 245, loss = 5.95380727
Iteration 246, loss = 5.95914693
Iteration 247, loss = 5.98626041
Iteration 248, loss = 5.97387720
Iteration 249, loss = 6.02304570
Iteration 250, loss = 5.90315693
Iteration 251, loss = 5.92870185
Iteration 252, loss = 5.96665293
Iteration 253, loss = 5.92494349
Iteration 254, loss = 5.93463072
Iteration 255, loss = 5.90097070
Iteration 256, loss = 5.91917070
Iteration 257, loss = 5.99436988
Iteration 258, loss = 5.88348767
Iteration 259, loss = 5.94463675
Iteration 260, loss = 5.90731404
Iteration 261, loss = 5.88635563
Iteration 262, loss = 5.87501301
Iteration 263, loss = 5.90679166
Iteration 264, loss = 5.91787457
Iteration 265, loss = 5.92113735
Iteration 266, loss = 5.89029887
Iteration 267, loss = 5.87649887
Iteration 268, loss = 5.83212104
Iteration 269, loss = 5.86776989
Iteration 270, loss = 5.88882952
Iteration 271, loss = 5.81601543
Iteration 272, loss = 5.89017902
Iteration 273, loss = 5.79947309
Iteration 274, loss = 5.85641512
Iteration 275, loss = 5.87025391
Iteration 276, loss = 5.89895703
Iteration 277, loss = 5.84938008
Iteration 278, loss = 5.83818511
Iteration 279, loss = 5.79773279
Iteration 280, loss = 5.82009145
Iteration 281, loss = 5.83842737
Iteration 282, loss = 5.81771877
Iteration 283, loss = 5.82086294
Iteration 284, loss = 5.81308664
Iteration 285, loss = 5.78411944
Iteration 286, loss = 5.87160185
Iteration 287, loss = 5.82914634
Iteration 288, loss = 5.76197474
Iteration 289, loss = 5.72793699
Iteration 290, loss = 5.84241185
Iteration 291, loss = 5.83707513
Iteration 292, loss = 5.80135334
Iteration 293, loss = 5.82888517
Iteration 294, loss = 5.80078897
Iteration 295, loss = 5.70030919
Iteration 296, loss = 5.83438252
Iteration 297, loss = 5.73029424
Iteration 298, loss = 5.75787510
Iteration 299, loss = 5.76858040
Iteration 300, loss = 5.76310429
Iteration 301, loss = 5.82674109
Iteration 302, loss = 5.70884331
Iteration 303, loss = 5.76994292
Iteration 304, loss = 5.71631708
Iteration 305, loss = 5.74441890
Iteration 306, loss = 5.74559037
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPRegressor(hidden_layer_sizes=(300, 255), max_iter=400, verbose=True)

## Predict on the test set

In [ ]:
predictions = mlp_regressor.predict(input_test)

## Evaluation the accuracy of fitted model

In [ ]:
mse = mean_squared_error(output_test, predictions)
print(f'Mean Squared Error: {mse}')

rmse = mean_squared_error(output_test, predictions, squared=False)
print(f'Root Mean Squared Error: {rmse}')

r2 = r2_score(output_test, predictions)
print(f'R-squared: {r2}')

Mean Squared Error: 11.707362831171825
Root Mean Squared Error: 3.4054991532061205
R-squared: 0.9991282711956632

# Train the model on evaluation dataset

In [ ]:
remained_evaluation

,pmax[0],negpmax[0],pmax[1],negpmax[1],area[1],rms[1],pmax[2],negpmax[2],area[2],pmax[3],...,area[15],rms[15],pmax[16],negpmax[16],area[16],rms[16],pmax[17],negpmax[17],area[17],rms[17]
0,4.400616,-4.257770,8.738040,-3.598874,5.554105,0.729175,5.359271,-4.603192,3.547230,11.347125,...,103.042194,1.084247,614.621212,-42.232574,583.237137,0.861022,608.931417,-42.728827,568.019556,0.328075
1,5.599571,-2.974570,23.460358,-20.616669,17.998419,1.258335,20.116995,-20.351328,11.315171,95.746893,...,160.806049,0.990254,520.333440,-36.986118,550.540448,0.259205,613.671695,-44.449564,586.292097,0.401326
2,3.731995,-5.662292,4.837952,-7.224267,3.289124,0.793541,6.132150,-4.086172,3.578799,7.510110,...,153.038339,1.619510,607.642389,-46.680069,582.825835,0.552691,608.996069,-45.877765,589.520958,0.343592
3,5.657729,-4.600342,87.293692,-45.786813,38.422989,0.733773,25.325571,-14.530936,10.306552,63.661270,...,157.042438,1.603065,596.094911,-48.241263,577.835129,0.361220,612.500144,-49.572583,583.795426,0.429650
4,3.716666,-4.583796,9.593125,-5.374179,7.767408,1.572473,6.618451,-4.427225,3.765579,13.074960,...,145.466171,1.249121,620.793628,-37.618567,599.834735,0.390639,621.557649,-45.189832,600.988676,0.358549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128495,5.847174,-3.001292,9.327438,-3.704605,6.657654,0.891158,4.763165,-4.856036,11.514778,7.936588,...,164.179764,1.575483,597.615085,-41.546677,586.379796,0.369140,598.153692,-44.463873,587.177692,0.391089
128496,3.965027,-5.731628,5.833882,-6.185739,4.184656,1.422575,3.790421,-5.154848,4.475711,4.913111,...,137.631274,1.210338,613.856352,-41.998062,585.524071,0.306312,618.483236,-42.177081,583.480972,0.342316
128497,3.630357,-5.045407,19.402353,-8.160696,11.304202,1.370319,17.555460,-8.818259,9.256798,115.297141,...,159.666370,1.308408,635.691002,-45.808194,585.666913,0.458888,592.747090,-49.569852,576.098097,0.274790
128498,3.690116,-5.391879,4.200095,-5.312485,2.652198,0.932871,2.959903,-4.739268,0.946364,8.768869,...,149.222157,1.713944,599.693287,-43.038669,576.129140,0.556171,603.034718,-45.188550,588.892068,0.510861
128499,4.999925,-2.938385,5.997916,-5.558389,3.536047,1.221496,5.532899,-4.497223,9.620306,4.825467,...,146.123618,0.853781,586.597873,-36.835648,589.797198,0.435812,622.379013,-49.490402,591.099715,0.332185

## Get ID of each records

In [ ]:
ID=evaluation['Id']
ID_frame=ID.to_frame()
ID_frame

            Id
0            0
1            1
2            2
3            3
4            4
...        ...
128495  128495
128496  128496
128497  128497
128498  128498
128499  128499

[128500 rows x 1 columns]

## Evaluation Dataset input

In [ ]:
e_input=evaluation.drop(columns=['Id'],axis=1)

In [ ]:
e_input

,pmax[0],negpmax[0],area[0],tmax[0],rms[0],pmax[1],negpmax[1],area[1],tmax[1],rms[1],...,pmax[16],negpmax[16],area[16],tmax[16],rms[16],pmax[17],negpmax[17],area[17],tmax[17],rms[17]
0,4.400616,-4.257770,2.860212,176.600000,1.562814,8.738040,-3.598874,5.554105,70.800000,0.729175,...,614.621212,-42.232574,583.237137,70.693530,0.861022,608.931417,-42.728827,568.019556,70.755552,0.328075
1,5.599571,-2.974570,9.400537,90.677386,1.129626,23.460358,-20.616669,17.998419,72.800000,1.258335,...,520.333440,-36.986118,550.540448,72.781390,0.259205,613.671695,-44.449564,586.292097,72.900695,0.401326
2,3.731995,-5.662292,1.930957,155.200000,0.921757,4.837952,-7.224267,3.289124,67.057395,0.793541,...,607.642389,-46.680069,582.825835,71.407320,0.552691,608.996069,-45.877765,589.520958,71.406020,0.343592
3,5.657729,-4.600342,5.593030,30.463179,1.269390,87.293692,-45.786813,38.422989,71.800000,0.733773,...,596.094911,-48.241263,577.835129,72.011986,0.361220,612.500144,-49.572583,583.795426,72.066338,0.429650
4,3.716666,-4.583796,1.946927,33.600000,1.082743,9.593125,-5.374179,7.767408,72.414459,1.572473,...,620.793628,-37.618567,599.834735,72.251813,0.390639,621.557649,-45.189832,600.988676,72.151243,0.358549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128495,5.847174,-3.001292,7.113683,184.584936,1.513353,9.327438,-3.704605,6.657654,71.400000,0.891158,...,597.615085,-41.546677,586.379796,71.379700,0.369140,598.153692,-44.463873,587.177692,71.567752,0.391089
128496,3.965027,-5.731628,1.695105,121.600000,1.566503,5.833882,-6.185739,4.184656,20.037256,1.422575,...,613.856352,-41.998062,585.524071,71.363987,0.306312,618.483236,-42.177081,583.480972,71.460047,0.342316
128497,3.630357,-5.045407,2.052289,115.074970,1.493089,19.402353,-8.160696,11.304202,70.800000,1.370319,...,635.691002,-45.808194,585.666913,70.661026,0.458888,592.747090,-49.569852,576.098097,70.806415,0.274790
128498,3.690116,-5.391879,3.624717,166.925787,1.132331,4.200095,-5.312485,2.652198,71.400000,0.932871,...,599.693287,-43.038669,576.129140,71.226970,0.556171,603.034718,-45.188550,588.892068,71.339138,0.510861
128499,4.999925,-2.938385,12.074915,165.282292,0.983532,5.997916,-5.558389,3.536047,72.000000,1.221496,...,586.597873,-36.835648,589.797198,72.106864,0.435812,622.379013,-49.490402,591.099715,72.067911,0.332185

## Normalizing evaluation input

In [ ]:
normalized_eval_input = normalize(remained_evaluation, norm='l2')
normalized_eval_input

array([[ 3.66401464e-03, -3.54507850e-03,  7.27541411e-03, ...,
        -3.55766172e-02,  4.72941005e-01,  2.73160148e-04],
       [ 4.80698173e-03, -2.55353545e-03,  2.01396710e-02, ...,
        -3.81579683e-02,  5.03305622e-01,  3.44520346e-04],
       [ 3.05678025e-03, -4.63783729e-03,  3.96264138e-03, ...,
        -3.75772904e-02,  4.82861366e-01,  2.81427247e-04],
       ...,
       [ 2.96664802e-03, -4.12299640e-03,  1.58551787e-02, ...,
        -4.05073993e-02,  4.70774772e-01,  2.24552216e-04],
       [ 3.05250427e-03, -4.46022109e-03,  3.47436387e-03, ...,
        -3.73804591e-02,  4.87137914e-01,  4.22589404e-04],
       [ 4.09561810e-03, -2.40693665e-03,  4.91310803e-03, ...,
        -4.05393651e-02,  4.84190996e-01,  2.72104759e-04]])

## Standardizing the normalized evaluation input

In [ ]:
standard_data_eval = (normalized_eval_input - np.mean(normalized_dev_input, axis=0)) / np.std(normalized_dev_input, axis=0)
standard_evaluation = pd.DataFrame(standard_data_eval, columns=remained_development.columns)
standard_evaluation

,pmax[0],negpmax[0],pmax[1],negpmax[1],area[1],rms[1],pmax[2],negpmax[2],area[2],pmax[3],...,area[15],rms[15],pmax[16],negpmax[16],area[16],rms[16],pmax[17],negpmax[17],area[17],rms[17]
0,-0.274715,0.126204,-0.456232,0.496662,-0.577638,-1.746980,-0.436224,0.155501,-0.566310,-0.589194,...,-2.906856,-0.775712,0.963011,-0.199654,0.648070,1.398879,0.547295,1.026964,-0.638915,-0.467999
1,0.665546,0.345276,0.478473,-1.137779,0.985575,-0.061201,1.594788,-1.979918,1.165335,2.900296,...,1.257847,-0.958405,-4.384524,1.083910,-0.722193,-0.607482,2.178426,0.135149,2.539722,0.585336
2,-0.774256,-0.115230,-0.696935,0.171960,-0.856365,-1.594305,-0.347342,0.231568,-0.571990,-0.747317,...,0.245966,0.694085,-0.190845,-1.354770,-0.220017,0.326659,-0.127383,0.335764,0.399571,-0.345970
3,0.548953,0.071350,4.245194,-3.367476,3.329297,-1.754344,2.167813,-1.120494,0.854108,1.475627,...,0.576303,0.677983,-0.698468,-1.935664,-0.315527,-0.301730,0.386773,-0.804091,0.245168,0.729417
4,-0.833736,0.096222,-0.425145,0.350029,-0.344769,0.588982,-0.301049,0.198972,-0.548307,-0.538761,...,-0.434776,-0.427864,-0.125723,1.664391,0.232162,-0.237496,-0.102920,0.781409,0.371488,-0.250214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128495,0.680883,0.362198,-0.425538,0.489891,-0.452008,-1.289657,-0.520463,0.128105,1.111410,-0.728194,...,1.054710,0.602981,-0.560489,0.129573,0.471289,-0.274162,-0.552476,0.640345,0.580853,0.264179
128496,-0.624096,-0.125114,-0.638556,0.267972,-0.751725,0.230908,-0.652774,0.096208,-0.386219,-0.849846,...,-0.782964,-0.477228,0.121389,0.120901,-0.116840,-0.494935,0.405479,1.413616,-0.246771,-0.372027
128497,-0.848403,-0.001481,0.167166,0.088412,0.088445,0.079798,1.131157,-0.372701,0.614824,3.477053,...,0.654552,-0.198381,1.598428,-1.053491,-0.091748,0.011321,-1.316075,-0.676541,-0.865681,-1.185492
128498,-0.777774,-0.075988,-0.732413,0.341237,-0.928575,-1.160613,-0.755567,0.141771,-1.122333,-0.694439,...,0.093603,1.010753,-0.324934,-0.364636,-0.304075,0.356590,-0.125411,0.403766,0.847250,1.737699
128499,0.080343,0.377665,-0.627875,0.323613,-0.827131,-0.345022,-0.425125,0.178807,0.695740,-0.852780,...,-0.204746,-1.481218,-1.604663,1.677276,0.385834,-0.061746,0.778577,-0.687585,0.538760,-0.483577

## Train the model

In [ ]:
e_predictions = mlp_regressor.predict(standard_evaluation)
e_predictions_df=pd.DataFrame(e_predictions, columns=['output1','output2'])
predictions_with_id= pd.concat([ID_frame,e_predictions_df],axis=1)
predictions_with_id

            Id     output1     output2
0            0  493.100753  326.397336
1            1  562.996456  582.102553
2            2  209.131998  394.127685
3            3  581.603543  512.209060
4            4  362.852825  363.741910
...        ...         ...         ...
128495  128495  440.005099  263.938905
128496  128496  279.931989  226.606695
128497  128497  455.210587  589.581130
128498  128498  230.461241  384.116013
128499  128499  407.651375  213.714302

[128500 rows x 3 columns]

## Generating CSV output

In [ ]:
new_df = pd.DataFrame({
    'Id': predictions_with_id['Id'],
    'Predicted': predictions_with_id['output1'].astype(str) + '|' + predictions_with_id['output2'].astype(str)
})


new_df.to_csv('MLP_norm_STD.csv', index=False)

# Visualize the Feature Importance

## Feature Importance Barchart

In [ ]:
sorted_feature_importance_name=sorted(zip(featureImportance, feature_names), reverse=True)
sorted_feature_importance_name

In [ ]:
import matplotlib.pyplot as plt

data =sorted_feature_importance_name

# Unpack the data
values, labels = zip(*data)

# Create a horizontal bar chart
plt.figure(figsize=(10, 15))  # Adjust the figure size as needed
plt.barh(labels, values, color='#1f77b4')  # Use 'barh' for horizontal bar chart
plt.xlabel('Feature Importance')
plt.ylabel('Features Name')


# Invert the Y-axis
plt.gca().invert_yaxis()

plt.show()

In [ ]:
import matplotlib.pyplot as plt

data = sorted_feature_importance_name

# Sort the data by the first column in descending order
sorted_data = sorted(data, key=lambda x: x[0], reverse=True)

# Select the top 25 values
top_25_values = sorted_data[:25]

# Unpack the top 25 data
values, labels = zip(*top_25_values)

# Create a horizontal bar chart
plt.figure(figsize=(10, 15))  # Adjust the figure size as needed
plt.barh(labels, values, color='#1f77b4')  # Use 'barh' for horizontal bar chart
plt.xlabel('Feature Importance')
plt.ylabel('Features Name')

# Invert the Y-axis
plt.gca().invert_yaxis()

# Save the plot as a PDF
plt.savefig("feature importance.pdf", bbox_inches="tight")

# Show the plot (optional)
plt.show()

#Euclidean Distance Plot

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

models_name = np.array(["MultiOutputRegressor", "DecisionTree", "RandomForest", "MultiLayerPerceptron"])
mse = np.array([140.625, 51.214, 15.172, 11.707])
ED = np.array([17.020, 8.599, 4.948, 4.114])

plt.figure(figsize=(5.5, 3))

# Change the color of the plot line to #1f77b4
plt.plot(models_name, ED, marker='.', color='#1f77b4', label='Euclidean distance')

plt.xlabel('Model Type')
plt.ylabel('Euclidean Distance')
plt.ylim(3, 18)
plt.legend()
plt.grid(True)

# Save the plot as a PDF with a border
plt.savefig("Euclidean Distance.pdf", bbox_inches="tight", edgecolor='black')

plt.show()

# Hyperparameter Configuration Plot

In [ ]:
import matplotlib.pyplot as plt

Hyperparameter_Configuration = [
    'HiddenLayer=(100,50),MaxIter=175',
    'HiddenLayer=(100,50),MaxIter=275',
    'HiddenLayer=(100,75,50,20),MaxIter=175',
    'HiddenLayer=(100,50,30,20,10),MaxIter=150',
    'HiddenLayer=(80,50,25,10),MaxIter=120',
    'HiddenLayer=(80,50,25,10,5),MaxIter=150',
    'HiddenLayer=(200,100),MaxIter=150',
    'HiddenLayer=(256,128,64,32),MaxIter=200',
    'HiddenLayer=(256,128,64,32),MaxIter=275',
    'HiddenLayer=(300,150,75),MaxIter=200',
    'HiddenLayer=(300,250,200),MaxIter=400',
    'HiddenLayer=(300,200),MaxIter=200',
    'HiddenLayer=(300,250),MaxIter=400',
    'HiddenLayer=(300,255),MaxIter=400',
]

ED = [8.348, 7.895, 7.112, 7.625, 7.203, 7.351, 6.132, 5.702, 4.967, 4.511, 4.313, 4.492, 4.329, 4.114]

plt.figure(figsize=(5.5, 3))
plt.scatter(ED, Hyperparameter_Configuration, cmap='viridis', marker='o', s=50)
plt.ylabel('Hyperparameters Configuration')
plt.xlabel('Euclidean distance')
plt.xlim(3.5, 8.5)
plt.legend()
plt.grid(True)

# Save the plot as a PDF
plt.savefig("Hyperparameter_Configuration.pdf", bbox_inches="tight")

plt.show()